/run/numberOfThreads 16
/run/initialize
/vis/open OGL
/vis/viewer/set/upVector 0 0 1
/vis/viewer/set/viewpointVector 1 1 1
/vis/drawVolume
/vis/viewer/set/autoRefresh true
/vis/scene/add/trajectories smooth
#/vis/scene/add/scale 10 cm
/vis/scene/add/axes
/vis/scene/add/eventID
/vis/scene/add/gps
/vis/scene/endOfEventAction accumulate

/gps/particle mu-
/gps/pos/type Surface
/gps/pos/shape Sphere
/gps/pos/centre 0 0 0 cm
/gps/pos/radius 10 cm
/gps/ang/type user
/gps/hist/type theta
/gps/hist/point 0.0   0.0
/gps/hist/point 0.2   0.19
/gps/hist/point 0.4   0.33
/gps/hist/point 0.6   0.36
/gps/hist/point 0.8   0.27
/gps/hist/point 1.0   0.0
/gps/ang/mintheta 0 deg
/gps/ang/maxtheta 90 deg
/gps/ene/type Mono
/gps/ene/mono 1 GeV


