/run/numberOfThreads 16
/run/initialize
/vis/open OGL
/vis/viewer/set/upVector 0 0 1
/vis/viewer/set/viewpointVector 1 1 1
/vis/drawVolume
/vis/viewer/set/autoRefresh true
/vis/scene/add/trajectories smooth
#/vis/scene/add/scale 10 cm
/vis/scene/add/axes
/vis/scene/add/eventID
/vis/scene/add/gps
/vis/scene/endOfEventAction accumulate

/gps/particle mu-
/gps/pos/type Surface
/gps/pos/shape Sphere
/gps/pos/centre 0 0 0 cm
/gps/pos/radius 20 cm
/gps/ang/type user
/gps/hist/type theta
/gps/hist/point 0.0392699 0.092033
/gps/hist/point 0.11781 0.273045
/gps/hist/point 0.19635 0.441198
/gps/hist/point 0.274889 0.59039
/gps/hist/point 0.353429 0.716355
/gps/hist/point 0.431969 0.814075
/gps/hist/point 0.510509 0.875174
/gps/hist/point 0.589049 0.903367
/gps/hist/point 0.667588 0.897453
/gps/hist/point 0.746128 0.860627
/gps/hist/point 0.824668 0.797552
/gps/hist/point 0.903208 0.708302
/gps/hist/point 0.981748 0.604058
/gps/hist/point 1.06029 0.489613
/gps/hist/point 1.13883 0.375879
/gps/hist/point 1.21737 0.265915
/gps/hist/point 1.29591 0.167478
/gps/hist/point 1.37445 0.089172
/gps/hist/point 1.45299 0.033459
/gps/hist/point 1.53153 0.004855
/gps/ene/type Mono
/gps/ene/mono 1 GeV


